### ISSUE TITLE
ValueError: Variable char_embedding/char_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope

### ISSUE THREAD

**Issue by guorouda** [yihenglu/chinese-address-segment#3]
2020-05-11 10:54:13.184921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1375 MB memory) -> physical GPU (device: 0, name: GeForce GTX 950, pci bus id: 0000:01:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "train_eval.py", line 269, in <module>
    tf.compat.v1.app.run(main)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_eval.py", line 263, in main
    train_test(FLAGS, FLAGS.train, FLAGS.dev, FLAGS.test)
  File "train_eval.py", line 186, in train_test
    model = create_model(sess, Model, FLAGS.ckpt_path, load_word2vec, config, id_to_char, logger)
  File "D:\study\chinese-address-segment\utils.py", line 172, in create_model
    model = Model_class(config)
  File "D:\study\chinese-address-segment\model.py", line 78, in __init__
    embedding = self.embedding_layer(self.char_inputs, self.seg_inputs, config)
  File "D:\study\chinese-address-segment\model.py", line 142, in embedding_layer
    initializer=self.initializer)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1496, in get_variable
    aggregation=aggregation)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1239, in get_variable
    aggregation=aggregation)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 562, in get_variable
    aggregation=aggregation)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 514, in _true_getter
    aggregation=aggregation)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 864, in _get_single_variable
    (err_msg, "".join(traceback.format_list(tb))))
ValueError: Variable char_embedding/char_embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 1609, in variable_v2
    shared_name=shared_name, name=name)

这个错误的原因是什么？请指点一下。

**Comment by guorouda** [comment]
这不是个问题
